site_name: BBFDM
site_url: https://dev.iopsys.eu/bbf/bbfdm
edit_uri: "https://dev.iopsys.eu/bbf/bbfdm"

site_description: BroadBand Forum Data Models (BBFDM)
site_author: IOPSYS

docs_dir: 'docs'
site_dir: 'site'

