#!/bin/sh
# Copyright (C) 2019 iopsys Software Solutions AB
# Author: AMIN Ben Ramdhane <amin.benramdhane@pivasoftware.com>

UCI_GET_BBFDM="/sbin/uci -q -c /etc/bbfdm get"
UCI_SET_BBFDM="/sbin/uci -q -c /etc/bbfdm set"
UCI_ADD_BBFDM="/sbin/uci -q -c /etc/bbfdm add"
UCI_DELETE_BBFDM="/sbin/uci -q -c /etc/bbfdm delete"
UCI_COMMIT_BBFDM="/sbin/uci -q -c /etc/bbfdm commit"
UCI_SHOW_BBFDM="/sbin/uci -q -c /etc/bbfdm show"

traceroute_get() {
	local val=`$UCI_GET_BBFDM $1`
	echo ${val:-$2}
}

traceroute_launch() {
	local i proto device res host ip time=0
	local host=`traceroute_get dmmap_diagnostics.traceroute.Host`
	local cnt=`traceroute_get dmmap_diagnostics.traceroute.NumberOfTries 3`
	local dsize=`traceroute_get dmmap_diagnostics.traceroute.DataBlockSize 38`
	local timeout=`traceroute_get dmmap_diagnostics.traceroute.Timeout 5000`
	local maxhop=`traceroute_get dmmap_diagnostics.traceroute.MaxHops 30`
	local interface=`traceroute_get dmmap_diagnostics.traceroute.interface`
	local protocol=`traceroute_get dmmap_diagnostics.traceroute.ProtocolVersion Any`
	[ ! -z "$interface" ] && device=`ifstatus $interface | jsonfilter -e @.device` && device="-i $device" || device=""
	if [ "$protocol" == "IPv4" ]; then proto="-4"; elif [ "$protocol" == "IPv6" ]; then proto="-6"; else proto=""; fi
	[ "$host" = "" ] && return
	timeout=$((timeout/1000))
	[ "$timeout" = "0" ] && timeout = "1"
	i=-2
	delete_all_route_hops
	rm -f /tmp/traceres
	traceroute -m $maxhop -w $timeout -q $cnt $proto $device $host $dsize 2>&1 >/tmp/traceres
	while read _ host ip time _; do
		[ "$host" = "*" -a "$ip" = "*" ] && continue
		let i++
		[ "$i" = "-1" ] && continue;
		ip=${ip#(}; ip=${ip%)}
		time=${time%.*}
		$UCI_ADD_BBFDM dmmap_diagnostics RouteHops
		$UCI_SET_BBFDM dmmap_diagnostics.@RouteHops[$i].host=$host
		$UCI_SET_BBFDM dmmap_diagnostics.@RouteHops[$i].ip=$ip
		$UCI_SET_BBFDM dmmap_diagnostics.@RouteHops[$i].time=$time
	done < /tmp/traceres
	rm -f /tmp/traceres
	let i++

	$UCI_SET_BBFDM dmmap_diagnostics.traceroute.DiagnosticState=Complete
	$UCI_SET_BBFDM dmmap_diagnostics.traceroute.NumberOfHops=$i
	$UCI_SET_BBFDM dmmap_diagnostics.traceroute.ResponseTime=$($UCI_GET_BBFDM dmmap_diagnostics.@RouteHops[-1].time)
	$UCI_COMMIT_BBFDM
}

delete_all_route_hops() {
	local j
	for j in $($UCI_SHOW_BBFDM dmmap_diagnostics | grep "dmmap_diagnostics.@RouteHops.*=RouteHops"); do
		$UCI_DELETE_BBFDM dmmap_diagnostics.@RouteHops[-1]
		$UCI_COMMIT_BBFDM
	done
}

traceroute_stop() {
	delete_all_route_hops
	local pids=`ps aux | grep traceroute_launch | grep -v grep | grep -v stop | awk '{print $2}'`
	[ -z "$pids" ] && pids=`ps | grep traceroute_launch | grep -v grep | grep -v stop | awk '{print $2}'`
	if [ -n "$pids" ]; then
		kill -9 $pids 2>/dev/null
		$UCI_SET_BBFDM dmmap_diagnostics.traceroute.DiagnosticState=None
		$UCI_COMMIT_BBFDM
	fi
}

if [ "$1" == "run" ]; then
	traceroute_launch 2>/dev/null  
elif [ "$1" == "stop" ]; then
	traceroute_stop 2>/dev/null
else
	return
fi
