include:
  - project: 'iopsys/gitlab-ci-pipeline'
    file: '/static-code-analysis.yml'

variables:
  COMMON_IMAGE: iopsys/code-analysis:0.26
  DEBUG: 'TRUE'
  SOURCE_FOLDER: "./src"
  RUN_CPPCHECK: "cppcheck --enable=all --error-exitcode=1 --inline-suppr --suppress=missingInclude --include=/usr/include/libubox/list.h -DUSPD_MAX_MSG_LEN=1048576"

stages:
    - static_code_analysis
    - test

run_unit_test:
    stage: test
    image: iopsys/code-analysis:latest
    allow_failure: false
    script:
    - "./gitlab-ci/install-dependencies.sh"
    - "./gitlab-ci/setup.sh"
    - "./gitlab-ci/unit-test.sh"
    artifacts:
        untracked: true
        when: always
        paths:
            - timestamp.log
            - unit-test-coverage.xml

run_functional_test:
    stage: test
    image: iopsys/code-analysis:latest
    allow_failure: false
    script:
    - "./gitlab-ci/install-dependencies.sh"
    - "./gitlab-ci/setup.sh"
    - "./gitlab-ci/functional-test.sh"

    artifacts:
        untracked: true
        when: always
        reports:
            junit: ./report/*.xml
        paths:
            - funl-result.log
            - funl-test-coverage.xml
            - memory-report.xml
            - timestamp.log
            - report/

run_api_test:
    stage: test
    image: iopsys/code-analysis:latest
    allow_failure: false
    script:
    - "./gitlab-ci/install-dependencies.sh"
    - "./gitlab-ci/setup.sh"
    - "./gitlab-ci/functional-api-test.sh"

    artifacts:
        untracked: true
        when: always
        reports:
            junit: ./report/*.xml
        paths:
            - timestamp.log
            - api-test-coverage.xml
            - memory-report.xml
            - api-result.log
            - report/

