#!/bin/sh

. /usr/share/libubox/jshn.sh

case "$1" in
        list)
                echo '{ "status" : {} }'
        ;;
        call)
                case "$2" in
                        status)
                                cat /tmp/dect.data
                        ;;
                esac
        ;;
esac

