#!/bin/sh

. /usr/share/libubox/jshn.sh

case "$1" in
        list)
                echo '{ "ipv6leases" : {} }'
        ;;
        call)
                case "$2" in
                        ipv6leases)
                                cat /tmp/dhcp.ipv6leases.data 2>/dev/null
                        ;;
                esac
        ;;
esac

