#!/bin/sh

. /usr/share/libubox/jshn.sh

case "$1" in
        list)
                echo '{ "info" : {} }'
        ;;
        call)
                case "$2" in
                        info)
                                cat /tmp/ieee1905.info.data 2>/dev/null
                        ;;
                esac
        ;;
esac

